// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'2e6aa8aee3c05b5b5d4ab1bbd9f148831256efa482a56c3e30c9022937fc47f3'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Cliente: {
      readonly idCliente: CodecTypes['pg/int4@1']['output'];
      readonly nome: Varchar<50>;
      readonly cpf: Varchar<15>;
      readonly telefone: Varchar<15>;
      readonly endereco: Varchar<50>;
      readonly email: Varchar<50> | null;
    };
    readonly FormaPagto: {
      readonly idFormaPgto: CodecTypes['pg/int4@1']['output'];
      readonly descricao: Varchar<50>;
    };
    readonly Funcionario: {
      readonly idFuncionario: CodecTypes['pg/int4@1']['output'];
      readonly nome: Varchar<50>;
      readonly cpf: Varchar<50>;
      readonly telefone: Varchar<15>;
      readonly email: Varchar<50>;
      readonly dataAdmissao: CodecTypes['pg/date-temporal@1']['output'] | null;
      readonly idUsuario: CodecTypes['pg/int4@1']['output'] | null;
      readonly salario: CodecTypes['pg/float8@1']['output'] | null;
    };
    readonly ItemVenda: {
      readonly idVenda: CodecTypes['pg/int4@1']['output'];
      readonly idProduto: CodecTypes['pg/int4@1']['output'];
    };
    readonly Login: {
      readonly iditemUsuario: CodecTypes['pg/int4@1']['output'];
      readonly descricao: Varchar<50>;
    };
    readonly Produto: {
      readonly idProduto: CodecTypes['pg/int4@1']['output'];
      readonly codBarras: CodecTypes['pg/numeric@1']['output'];
      readonly descricao: Varchar<50>;
      readonly categoria: Varchar<50>;
      readonly quantidade: CodecTypes['pg/int4@1']['output'];
      readonly preco: CodecTypes['pg/float8@1']['output'];
      readonly precoOriginal: CodecTypes['pg/float8@1']['output'] | null;
      readonly parcelas: CodecTypes['pg/int4@1']['output'] | null;
      readonly idCategoria: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly TipoProduto: {
      readonly idCategoria: CodecTypes['pg/int4@1']['output'];
      readonly categoria: Varchar<50>;
    };
    readonly Venda: {
      readonly idVenda: CodecTypes['pg/int4@1']['output'];
      readonly dataVenda: CodecTypes['pg/date-temporal@1']['output'];
      readonly produto: Varchar<50>;
      readonly quantidade: CodecTypes['pg/int4@1']['output'];
      readonly preco: CodecTypes['pg/float8@1']['output'];
      readonly totalVenda: CodecTypes['pg/float8@1']['output'];
      readonly idFormaPgto: CodecTypes['pg/int4@1']['output'];
      readonly idFuncionario: CodecTypes['pg/int4@1']['output'] | null;
      readonly idCliente: CodecTypes['pg/int4@1']['output'] | null;
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly idPagamentoExterno: CodecTypes['pg/text@1']['output'] | null;
      readonly linkPagamento: CodecTypes['pg/text@1']['output'] | null;
      readonly dadosCliente: CodecTypes['pg/text@1']['output'] | null;
      readonly observacoes: CodecTypes['pg/text@1']['output'] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Cliente: {
      readonly idCliente: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['sql/varchar@1']['input'];
      readonly cpf: CodecTypes['sql/varchar@1']['input'];
      readonly telefone: CodecTypes['sql/varchar@1']['input'];
      readonly endereco: CodecTypes['sql/varchar@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'] | null;
    };
    readonly FormaPagto: {
      readonly idFormaPgto: CodecTypes['pg/int4@1']['input'];
      readonly descricao: CodecTypes['sql/varchar@1']['input'];
    };
    readonly Funcionario: {
      readonly idFuncionario: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['sql/varchar@1']['input'];
      readonly cpf: CodecTypes['sql/varchar@1']['input'];
      readonly telefone: CodecTypes['sql/varchar@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly dataAdmissao: CodecTypes['pg/date-temporal@1']['input'] | null;
      readonly idUsuario: CodecTypes['pg/int4@1']['input'] | null;
      readonly salario: CodecTypes['pg/float8@1']['input'] | null;
    };
    readonly ItemVenda: {
      readonly idVenda: CodecTypes['pg/int4@1']['input'];
      readonly idProduto: CodecTypes['pg/int4@1']['input'];
    };
    readonly Login: {
      readonly iditemUsuario: CodecTypes['pg/int4@1']['input'];
      readonly descricao: CodecTypes['sql/varchar@1']['input'];
    };
    readonly Produto: {
      readonly idProduto: CodecTypes['pg/int4@1']['input'];
      readonly codBarras: CodecTypes['pg/numeric@1']['input'];
      readonly descricao: CodecTypes['sql/varchar@1']['input'];
      readonly categoria: CodecTypes['sql/varchar@1']['input'];
      readonly quantidade: CodecTypes['pg/int4@1']['input'];
      readonly preco: CodecTypes['pg/float8@1']['input'];
      readonly precoOriginal: CodecTypes['pg/float8@1']['input'] | null;
      readonly parcelas: CodecTypes['pg/int4@1']['input'] | null;
      readonly idCategoria: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly TipoProduto: {
      readonly idCategoria: CodecTypes['pg/int4@1']['input'];
      readonly categoria: CodecTypes['sql/varchar@1']['input'];
    };
    readonly Venda: {
      readonly idVenda: CodecTypes['pg/int4@1']['input'];
      readonly dataVenda: CodecTypes['pg/date-temporal@1']['input'];
      readonly produto: CodecTypes['sql/varchar@1']['input'];
      readonly quantidade: CodecTypes['pg/int4@1']['input'];
      readonly preco: CodecTypes['pg/float8@1']['input'];
      readonly totalVenda: CodecTypes['pg/float8@1']['input'];
      readonly idFormaPgto: CodecTypes['pg/int4@1']['input'];
      readonly idFuncionario: CodecTypes['pg/int4@1']['input'] | null;
      readonly idCliente: CodecTypes['pg/int4@1']['input'] | null;
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly idPagamentoExterno: CodecTypes['pg/text@1']['input'] | null;
      readonly linkPagamento: CodecTypes['pg/text@1']['input'] | null;
      readonly dadosCliente: CodecTypes['pg/text@1']['input'] | null;
      readonly observacoes: CodecTypes['pg/text@1']['input'] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly Cliente: {
      readonly cpf: Varchar<15>;
      readonly email: Varchar<50> | null;
      readonly endereco: Varchar<50>;
      readonly idCliente: CodecTypes['pg/int4@1']['output'];
      readonly nome: Varchar<50>;
      readonly telefone: Varchar<15>;
    };
    readonly FormaPagto: {
      readonly descricao: Varchar<50>;
      readonly idFormaPgto: CodecTypes['pg/int4@1']['output'];
    };
    readonly Funcionario: {
      readonly cpf: Varchar<50>;
      readonly dataAdmissao: CodecTypes['pg/date-temporal@1']['output'] | null;
      readonly email: Varchar<50>;
      readonly idFunconario: CodecTypes['pg/int4@1']['output'];
      readonly idUsuario: CodecTypes['pg/int4@1']['output'] | null;
      readonly nome: Varchar<50>;
      readonly salario: CodecTypes['pg/float8@1']['output'] | null;
      readonly telefone: Varchar<15>;
    };
    readonly item_venda: {
      readonly idProduto: CodecTypes['pg/int4@1']['output'];
      readonly idVenda: CodecTypes['pg/int4@1']['output'];
    };
    readonly Login: {
      readonly descricao: Varchar<50>;
      readonly iditemUsuario: CodecTypes['pg/int4@1']['output'];
    };
    readonly Produto: {
      readonly categoria: Varchar<50>;
      readonly cod_Barras: CodecTypes['pg/numeric@1']['output'];
      readonly descricao: Varchar<50>;
      readonly idCategoria: CodecTypes['pg/int4@1']['output'] | null;
      readonly idProduto: CodecTypes['pg/int4@1']['output'];
      readonly parcelas: CodecTypes['pg/int4@1']['output'] | null;
      readonly preco: CodecTypes['pg/float8@1']['output'];
      readonly preco_original: CodecTypes['pg/float8@1']['output'] | null;
      readonly quantidade: CodecTypes['pg/int4@1']['output'];
    };
    readonly Tipo_produto: {
      readonly categoria: Varchar<50>;
      readonly idCategoria: CodecTypes['pg/int4@1']['output'];
    };
    readonly Venda: {
      readonly dadosCliente: CodecTypes['pg/text@1']['output'] | null;
      readonly dataVenda: CodecTypes['pg/date-temporal@1']['output'];
      readonly idCliente: CodecTypes['pg/int4@1']['output'] | null;
      readonly idFormaPgto: CodecTypes['pg/int4@1']['output'];
      readonly idFuncionario: CodecTypes['pg/int4@1']['output'] | null;
      readonly idPagamentoExterno: CodecTypes['pg/text@1']['output'] | null;
      readonly idVenda: CodecTypes['pg/int4@1']['output'];
      readonly linkPagamento: CodecTypes['pg/text@1']['output'] | null;
      readonly observacoes: CodecTypes['pg/text@1']['output'] | null;
      readonly preco: CodecTypes['pg/float8@1']['output'];
      readonly produto: Varchar<50>;
      readonly quantidade: CodecTypes['pg/int4@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly Total_Venda: CodecTypes['pg/float8@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly Cliente: {
      readonly cpf: CodecTypes['sql/varchar@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'] | null;
      readonly endereco: CodecTypes['sql/varchar@1']['input'];
      readonly idCliente: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['sql/varchar@1']['input'];
      readonly telefone: CodecTypes['sql/varchar@1']['input'];
    };
    readonly FormaPagto: {
      readonly descricao: CodecTypes['sql/varchar@1']['input'];
      readonly idFormaPgto: CodecTypes['pg/int4@1']['input'];
    };
    readonly Funcionario: {
      readonly cpf: CodecTypes['sql/varchar@1']['input'];
      readonly dataAdmissao: CodecTypes['pg/date-temporal@1']['input'] | null;
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly idFunconario: CodecTypes['pg/int4@1']['input'];
      readonly idUsuario: CodecTypes['pg/int4@1']['input'] | null;
      readonly nome: CodecTypes['sql/varchar@1']['input'];
      readonly salario: CodecTypes['pg/float8@1']['input'] | null;
      readonly telefone: CodecTypes['sql/varchar@1']['input'];
    };
    readonly item_venda: {
      readonly idProduto: CodecTypes['pg/int4@1']['input'];
      readonly idVenda: CodecTypes['pg/int4@1']['input'];
    };
    readonly Login: {
      readonly descricao: CodecTypes['sql/varchar@1']['input'];
      readonly iditemUsuario: CodecTypes['pg/int4@1']['input'];
    };
    readonly Produto: {
      readonly categoria: CodecTypes['sql/varchar@1']['input'];
      readonly cod_Barras: CodecTypes['pg/numeric@1']['input'];
      readonly descricao: CodecTypes['sql/varchar@1']['input'];
      readonly idCategoria: CodecTypes['pg/int4@1']['input'] | null;
      readonly idProduto: CodecTypes['pg/int4@1']['input'];
      readonly parcelas: CodecTypes['pg/int4@1']['input'] | null;
      readonly preco: CodecTypes['pg/float8@1']['input'];
      readonly preco_original: CodecTypes['pg/float8@1']['input'] | null;
      readonly quantidade: CodecTypes['pg/int4@1']['input'];
    };
    readonly Tipo_produto: {
      readonly categoria: CodecTypes['sql/varchar@1']['input'];
      readonly idCategoria: CodecTypes['pg/int4@1']['input'];
    };
    readonly Venda: {
      readonly dadosCliente: CodecTypes['pg/text@1']['input'] | null;
      readonly dataVenda: CodecTypes['pg/date-temporal@1']['input'];
      readonly idCliente: CodecTypes['pg/int4@1']['input'] | null;
      readonly idFormaPgto: CodecTypes['pg/int4@1']['input'];
      readonly idFuncionario: CodecTypes['pg/int4@1']['input'] | null;
      readonly idPagamentoExterno: CodecTypes['pg/text@1']['input'] | null;
      readonly idVenda: CodecTypes['pg/int4@1']['input'];
      readonly linkPagamento: CodecTypes['pg/text@1']['input'] | null;
      readonly observacoes: CodecTypes['pg/text@1']['input'] | null;
      readonly preco: CodecTypes['pg/float8@1']['input'];
      readonly produto: CodecTypes['sql/varchar@1']['input'];
      readonly quantidade: CodecTypes['pg/int4@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly Total_Venda: CodecTypes['pg/float8@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly Cliente: {
              columns: {
                readonly idCliente: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly cpf: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 15 };
                };
                readonly telefone: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 15 };
                };
                readonly endereco: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly email: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 50 };
                };
              };
              primaryKey: { readonly columns: readonly ['idCliente'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly FormaPagto: {
              columns: {
                readonly idFormaPgto: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly descricao: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
              };
              primaryKey: { readonly columns: readonly ['idFormaPgto'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Funcionario: {
              columns: {
                readonly idFunconario: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly cpf: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly telefone: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 15 };
                };
                readonly email: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly dataAdmissao: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: true;
                };
                readonly idUsuario: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly salario: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['idFunconario'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Funcionario_idUsuario_idx_2255b915';
                  readonly prefix: 'Funcionario_idUsuario_idx';
                  readonly columns: readonly ['idUsuario'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Funcionario';
                    readonly columns: readonly ['idUsuario'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Login';
                    readonly columns: readonly ['iditemUsuario'];
                  };
                  readonly name: 'FK_idUsuario';
                },
              ];
            };
            readonly item_venda: {
              columns: {
                readonly idVenda: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly idProduto: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['idVenda', 'idProduto'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'item_venda_idVenda_idx_7d9ee885';
                  readonly prefix: 'item_venda_idVenda_idx';
                  readonly columns: readonly ['idVenda'];
                  readonly unique: false;
                },
                {
                  readonly name: 'item_venda_idProduto_idx_5613a5d0';
                  readonly prefix: 'item_venda_idProduto_idx';
                  readonly columns: readonly ['idProduto'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'item_venda';
                    readonly columns: readonly ['idVenda'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Venda';
                    readonly columns: readonly ['idVenda'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'item_venda';
                    readonly columns: readonly ['idProduto'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Produto';
                    readonly columns: readonly ['idProduto'];
                  };
                },
              ];
            };
            readonly Login: {
              columns: {
                readonly iditemUsuario: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly descricao: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
              };
              primaryKey: { readonly columns: readonly ['iditemUsuario'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Produto: {
              columns: {
                readonly idProduto: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly cod_Barras: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly descricao: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly categoria: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly quantidade: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly preco: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly preco_original: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly parcelas: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
                readonly idCategoria: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['idProduto'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Produto_idCategoria_idx_430ced79';
                  readonly prefix: 'Produto_idCategoria_idx';
                  readonly columns: readonly ['idCategoria'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Produto';
                    readonly columns: readonly ['idCategoria'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Tipo_produto';
                    readonly columns: readonly ['idCategoria'];
                  };
                  readonly name: 'FK_idCategoria';
                },
              ];
            };
            readonly Tipo_produto: {
              columns: {
                readonly idCategoria: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly categoria: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
              };
              primaryKey: { readonly columns: readonly ['idCategoria'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Venda: {
              columns: {
                readonly idVenda: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly dataVenda: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: false;
                };
                readonly produto: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
                readonly quantidade: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly preco: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly Total_Venda: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly idFormaPgto: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly idFuncionario: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly idCliente: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'pendente'>;
                  };
                };
                readonly idPagamentoExterno: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly linkPagamento: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly dadosCliente: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly observacoes: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['idVenda'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Venda_idCliente_idx_f51e9825';
                  readonly prefix: 'Venda_idCliente_idx';
                  readonly columns: readonly ['idCliente'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Venda_idFuncionario_idx_a3fb447f';
                  readonly prefix: 'Venda_idFuncionario_idx';
                  readonly columns: readonly ['idFuncionario'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Venda_idFormaPgto_idx_1e5a0c4a';
                  readonly prefix: 'Venda_idFormaPgto_idx';
                  readonly columns: readonly ['idFormaPgto'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Venda';
                    readonly columns: readonly ['idCliente'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Cliente';
                    readonly columns: readonly ['idCliente'];
                  };
                  readonly name: 'FK_idCliente';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Venda';
                    readonly columns: readonly ['idFuncionario'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Funcionario';
                    readonly columns: readonly ['idFunconario'];
                  };
                  readonly name: 'FK_idFuncionario';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Venda';
                    readonly columns: readonly ['idFormaPgto'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'FormaPagto';
                    readonly columns: readonly ['idFormaPgto'];
                  };
                  readonly name: 'FK_idFormaPgto';
                },
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly Cliente: { readonly namespace: 'public' & NamespaceId; readonly model: 'Cliente' };
    readonly Produto: { readonly namespace: 'public' & NamespaceId; readonly model: 'Produto' };
    readonly Tipo_produto: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'TipoProduto';
    };
    readonly Funcionario: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Funcionario';
    };
    readonly Login: { readonly namespace: 'public' & NamespaceId; readonly model: 'Login' };
    readonly item_venda: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ItemVenda';
    };
    readonly Venda: { readonly namespace: 'public' & NamespaceId; readonly model: 'Venda' };
    readonly FormaPagto: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'FormaPagto';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Cliente: {
            readonly fields: {
              readonly idCliente: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly cpf: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 15 };
                };
              };
              readonly telefone: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 15 };
                };
              };
              readonly endereco: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
            };
            readonly relations: {
              readonly vendas: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Venda';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['idCliente'];
                  readonly targetFields: readonly ['idCliente'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Cliente';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly idCliente: { readonly column: 'idCliente' };
                readonly nome: { readonly column: 'nome' };
                readonly cpf: { readonly column: 'cpf' };
                readonly telefone: { readonly column: 'telefone' };
                readonly endereco: { readonly column: 'endereco' };
                readonly email: { readonly column: 'email' };
              };
            };
          };
          readonly FormaPagto: {
            readonly fields: {
              readonly idFormaPgto: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly descricao: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'FormaPagto';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly idFormaPgto: { readonly column: 'idFormaPgto' };
                readonly descricao: { readonly column: 'descricao' };
              };
            };
          };
          readonly Funcionario: {
            readonly fields: {
              readonly idFuncionario: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly cpf: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly telefone: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 15 };
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly dataAdmissao: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly idUsuario: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly salario: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
            };
            readonly relations: {
              readonly login: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Login';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['idUsuario'];
                  readonly targetFields: readonly ['iditemUsuario'];
                };
              };
              readonly vendas: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Venda';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['idFuncionario'];
                  readonly targetFields: readonly ['idFuncionario'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Funcionario';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly idFuncionario: { readonly column: 'idFunconario' };
                readonly nome: { readonly column: 'nome' };
                readonly cpf: { readonly column: 'cpf' };
                readonly telefone: { readonly column: 'telefone' };
                readonly email: { readonly column: 'email' };
                readonly dataAdmissao: { readonly column: 'dataAdmissao' };
                readonly idUsuario: { readonly column: 'idUsuario' };
                readonly salario: { readonly column: 'salario' };
              };
            };
          };
          readonly ItemVenda: {
            readonly fields: {
              readonly idVenda: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly idProduto: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly produto: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Produto';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['idProduto'];
                  readonly targetFields: readonly ['idProduto'];
                };
              };
              readonly venda: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Venda';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['idVenda'];
                  readonly targetFields: readonly ['idVenda'];
                };
              };
            };
            readonly storage: {
              readonly table: 'item_venda';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly idVenda: { readonly column: 'idVenda' };
                readonly idProduto: { readonly column: 'idProduto' };
              };
            };
          };
          readonly Login: {
            readonly fields: {
              readonly iditemUsuario: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly descricao: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
            };
            readonly relations: {
              readonly funcionarios: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Funcionario';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['iditemUsuario'];
                  readonly targetFields: readonly ['idUsuario'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Login';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly iditemUsuario: { readonly column: 'iditemUsuario' };
                readonly descricao: { readonly column: 'descricao' };
              };
            };
          };
          readonly Produto: {
            readonly fields: {
              readonly idProduto: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly codBarras: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly descricao: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly categoria: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly quantidade: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly preco: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly precoOriginal: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly parcelas: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly idCategoria: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly tipoProduto: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'TipoProduto';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['idCategoria'];
                  readonly targetFields: readonly ['idCategoria'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Produto';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly idProduto: { readonly column: 'idProduto' };
                readonly codBarras: { readonly column: 'cod_Barras' };
                readonly descricao: { readonly column: 'descricao' };
                readonly categoria: { readonly column: 'categoria' };
                readonly quantidade: { readonly column: 'quantidade' };
                readonly preco: { readonly column: 'preco' };
                readonly precoOriginal: { readonly column: 'preco_original' };
                readonly parcelas: { readonly column: 'parcelas' };
                readonly idCategoria: { readonly column: 'idCategoria' };
              };
            };
          };
          readonly TipoProduto: {
            readonly fields: {
              readonly idCategoria: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly categoria: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
            };
            readonly relations: {
              readonly produtos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Produto';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['idCategoria'];
                  readonly targetFields: readonly ['idCategoria'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Tipo_produto';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly idCategoria: { readonly column: 'idCategoria' };
                readonly categoria: { readonly column: 'categoria' };
              };
            };
          };
          readonly Venda: {
            readonly fields: {
              readonly idVenda: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly dataVenda: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly produto: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
              readonly quantidade: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly preco: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly totalVenda: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly idFormaPgto: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly idFuncionario: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly idCliente: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly idPagamentoExterno: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly linkPagamento: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly dadosCliente: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly observacoes: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly cliente: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Cliente';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['idCliente'];
                  readonly targetFields: readonly ['idCliente'];
                };
              };
              readonly formaPagto: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'FormaPagto';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['idFormaPgto'];
                  readonly targetFields: readonly ['idFormaPgto'];
                };
              };
              readonly funcionario: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Funcionario';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['idFuncionario'];
                  readonly targetFields: readonly ['idFuncionario'];
                };
              };
              readonly itens: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ItemVenda';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['idVenda'];
                  readonly targetFields: readonly ['idVenda'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Venda';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly idVenda: { readonly column: 'idVenda' };
                readonly dataVenda: { readonly column: 'dataVenda' };
                readonly produto: { readonly column: 'produto' };
                readonly quantidade: { readonly column: 'quantidade' };
                readonly preco: { readonly column: 'preco' };
                readonly totalVenda: { readonly column: 'Total_Venda' };
                readonly idFormaPgto: { readonly column: 'idFormaPgto' };
                readonly idFuncionario: { readonly column: 'idFuncionario' };
                readonly idCliente: { readonly column: 'idCliente' };
                readonly status: { readonly column: 'status' };
                readonly idPagamentoExterno: { readonly column: 'idPagamentoExterno' };
                readonly linkPagamento: { readonly column: 'linkPagamento' };
                readonly dadosCliente: { readonly column: 'dadosCliente' };
                readonly observacoes: { readonly column: 'observacoes' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
